// Dog Model
/*
  Fields:
  - id: string (auto-generated by Firestore)
  - name: string
  - breed: string
  - age: number
  - weight: number (in pounds)
  - owner: string (user ID)
  - notes: string
  - medications: array of strings
  - allergies: array of strings
  - imageUrl: string (if there's a profile pic)
  - createdAt: timestamp
  - updatedAt: timestamp
*/

import { addDocument, updateDocument, deleteDocument, getDocument, queryCollection } from '../services/firebaseService';

const COLLECTION_NAME = 'dogs';

export const createDog = async (dogData) => {
  return await addDocument(COLLECTION_NAME, dogData);
};

export const updateDog = async (dogId, dogData) => {
  return await updateDocument(COLLECTION_NAME, dogId, dogData);
};

export const deleteDog = async (dogId) => {
  return await deleteDocument(COLLECTION_NAME, dogId);
};

export const getDog = async (dogId) => {
  return await getDocument(COLLECTION_NAME, dogId);
};

export const getDogsByOwner = async (ownerId) => {
  const conditions = [
    { field: 'owner', operator: '==', value: ownerId }
  ];
  const sortOptions = [
    { field: 'name', direction: 'asc' }
  ];
  
  return await queryCollection(COLLECTION_NAME, conditions, sortOptions);
}; 